apiVersion: v1
kind: Secret
metadata:
  name: bindass-secrets
type: Opaque
data:
  # Base64 encoded values
  MONGO_URI: bW9uZ29kYjovL2xvY2FsaG9zdDoyNzAxNy9iaW5kYXNzLWx1eHVyeQ==
  RAZORPAY_KEY_ID: eW91cl9rZXlfaWQ=
  RAZORPAY_KEY_SECRET: eW91cl9rZXlfc2VjcmV0
  GEMINI_API_KEY: eW91cl9nZW1pbmlfYXBpX2tleQ==
